### ISSUE TITLE
Remove unnecessary semicolons `;`

### ISSUE THREAD

**Issue by jmackie** [ditto-lang/ditto#162]
Semicolons are useful for facilitating code generation, but offend some people (@ivan-jukic :eyes:), so they can probably be made optional. 

I reckon we use [Go's heuristic](https://go.dev/doc/effective_go#semicolons) here.

`ditto-fmt` should also be updated to drop semicolons where possible?

**Comment by ivan-jukic** [comment]
Thanks bud, you're the best!

Wouldn't say they offend me, after all I'll be using them on a daily basis shortly. I suppose using Elm and Haskell (a little bit) I've sort of learned to appreciate their absence.
